import typing
from typing import Any

class Middleware:
    cls: Any = ...
    options: Any = ...
    def __init__(self, cls: type, **options: typing.Any) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
