import typing
from starlette.datastructures import MutableHeaders as MutableHeaders, Secret as Secret
from starlette.requests import HTTPConnection as HTTPConnection
from starlette.types import ASGIApp as ASGIApp, Message as Message, Receive as Receive, Scope as Scope, Send as Send
from typing import Any

class SessionMiddleware:
    app: Any = ...
    signer: Any = ...
    session_cookie: Any = ...
    max_age: Any = ...
    security_flags: Any = ...
    def __init__(self, app: ASGIApp, secret_key: typing.Union[str, Secret], session_cookie: str=..., max_age: int=..., same_site: str=..., https_only: bool=...) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
