import typing
from starlette.datastructures import Headers as Headers, URL as URL
from starlette.responses import PlainTextResponse as PlainTextResponse, RedirectResponse as RedirectResponse, Response as Response
from starlette.types import ASGIApp as ASGIApp, Receive as Receive, Scope as Scope, Send as Send
from typing import Any

ENFORCE_DOMAIN_WILDCARD: str

class TrustedHostMiddleware:
    app: Any = ...
    allowed_hosts: Any = ...
    allow_any: Any = ...
    www_redirect: Any = ...
    def __init__(self, app: ASGIApp, allowed_hosts: typing.Sequence[str]=..., www_redirect: bool=...) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
