from ...orm.scoping import ScopedSessionMixin as ScopedSessionMixin
from ...util import ScopedRegistry as ScopedRegistry, create_proxy_methods as create_proxy_methods
from .session import AsyncSession as AsyncSession
from typing import Any

class async_scoped_session(ScopedSessionMixin):
    session_factory: Any = ...
    registry: Any = ...
    def __init__(self, session_factory: Any, scopefunc: Any) -> None: ...
    async def remove(self) -> None: ...
