stages:
  - lint

step1:
  stage: lint
  image:
      name: docker pull $DOCKER_HOST/pyright-lint/pyright:1.1.166
  script:
    - pyright --version
    - pwd
  tags:
    - runner
  only:
    - master
    - dev
