"""
This type stub file was generated by pyright.
"""

from typing import Any

EMPTY_ANNOTATIONS: Any
class SupportsAnnotations:
    ...


class SupportsCloneAnnotations(SupportsAnnotations):
    ...


class SupportsWrappingAnnotations(SupportsAnnotations):
    ...


class Annotated:
    def __new__(cls, *args: Any):
        ...
    
    __dict__: Any = ...
    def __init__(self, element: Any, values: Any) -> None:
        ...
    
    def __reduce__(self):
        ...
    
    def __hash__(self) -> Any:
        ...
    
    def __eq__(self, other: Any) -> Any:
        ...
    
    @property
    def entity_namespace(self):
        ...
    


annotated_classes: Any
