from . import coercions as coercions, dml as dml, elements as elements, roles as roles
from .. import exc as exc, util as util
from typing import Any

REQUIRED: Any

class _multiparam_column(elements.ColumnElement):
    index: Any = ...
    key: Any = ...
    original: Any = ...
    default: Any = ...
    type: Any = ...
    def __init__(self, original: Any, index: Any) -> None: ...
    def compare(self, other: Any, **kw: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
