"""
This type stub file was generated by pyright.
"""

from typing import Any
from sqlalchemy.orm.query import Query

all_: Any
any_: Any
and_: Any
alias: Any
tablesample: Any
lateral: Any
or_: Any
bindparam: Any
select: Any
text: Any
table: Any
column: Any
over: Any
within_group: Any
label: Any
case: Any
cast: Any
cte: Any
values: Any
extract: Any
tuple_: Any
except_: Any
except_all: Any
intersect: Any
intersect_all: Any
union: Any
union_all: Any
exists: Any
nulls_first: Any
nullsfirst = nulls_first
nulls_last: Any
nullslast = nulls_last
asc: Any
desc: Any
distinct: Any
type_coerce: Any
null: Any
join: Any
outerjoin: Any
insert: Query
update: Query
delete: Query
