from pathlib import Path
from socket import socket
from typing import Any, Callable, Iterator, List, Optional
from uvicorn.config import Config as Config
from uvicorn.supervisors.basereload import BaseReload as BaseReload

logger: Any

class StatReload(BaseReload):
    reloader_name: str = ...
    mtimes: Any = ...
    def __init__(self, config: Config, target: Callable[[Optional[List[socket]]], None], sockets: List[socket]) -> None: ...
    def should_restart(self) -> bool: ...
    def restart(self) -> None: ...
    def iter_py_files(self) -> Iterator[Path]: ...
