from pathlib import Path
from socket import socket
from typing import Any, Callable, List, Optional
from uvicorn.config import Config as Config
from uvicorn.supervisors.basereload import BaseReload as BaseReload
from watchgod import DefaultWatcher

logger: Any
DirEntry: Any

class CustomWatcher(DefaultWatcher):
    includes: Any = ...
    excludes: Any = ...
    watched_dirs: Any = ...
    watched_files: Any = ...
    dirs_includes: Any = ...
    dirs_excludes: Any = ...
    resolved_root: Any = ...
    def __init__(self, root_path: Path, config: Config) -> None: ...
    def should_watch_file(self, entry: DirEntry) -> bool: ...
    def should_watch_dir(self, entry: DirEntry) -> bool: ...

class WatchGodReload(BaseReload):
    reloader_name: str = ...
    watchers: Any = ...
    def __init__(self, config: Config, target: Callable[[Optional[List[socket]]], None], sockets: List[socket]) -> None: ...
    def should_restart(self) -> bool: ...
