import typing as t
from _typeshed.wsgi import StartResponse, WSGIApplication as WSGIApplication, WSGIEnvironment as WSGIEnvironment
from typing import Any

class DispatcherMiddleware:
    app: Any = ...
    mounts: Any = ...
    def __init__(self, app: WSGIApplication, mounts: t.Optional[t.Dict[str, WSGIApplication]]=...) -> None: ...
    def __call__(self, environ: WSGIEnvironment, start_response: StartResponse) -> t.Iterable[bytes]: ...
