import typing as t
from ..http import parse_list_header as parse_list_header
from _typeshed.wsgi import StartResponse, WSGIApplication as WSGIApplication, WSGIEnvironment as WSGIEnvironment
from typing import Any

class ProxyFix:
    app: Any = ...
    x_for: Any = ...
    x_proto: Any = ...
    x_host: Any = ...
    x_port: Any = ...
    x_prefix: Any = ...
    def __init__(self, app: WSGIApplication, x_for: int=..., x_proto: int=..., x_host: int=..., x_port: int=..., x_prefix: int=...) -> None: ...
    def __call__(self, environ: WSGIEnvironment, start_response: StartResponse) -> t.Iterable[bytes]: ...
