from ...orm.decl_api import DeclarativeMeta as DeclarativeMeta, declared_attr as declared_attr
from .extensions import AbstractConcreteBase as AbstractConcreteBase, ConcreteBase as ConcreteBase, DeferredReflection as DeferredReflection, instrument_declarative as instrument_declarative
from typing import Any

def declarative_base(*arg: Any, **kw: Any): ...
def as_declarative(*arg: Any, **kw: Any): ...
def has_inherited_table(*arg: Any, **kw: Any): ...
def synonym_for(*arg: Any, **kw: Any): ...
