from uvicorn import Config as Config

class LifespanOff:
    should_exit: bool = ...
    def __init__(self, config: Config) -> None: ...
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
