"""
This type stub file was generated by pyright.
"""

import asyncio
from asgiref.typing import WWWScope as WWWScope
from typing import Optional, Tuple

def get_remote_addr(transport: asyncio.Transport) -> Optional[Tuple[str, int]]:
    ...

def get_local_addr(transport: asyncio.Transport) -> Optional[Tuple[str, int]]:
    ...

def is_ssl(transport: asyncio.Transport) -> bool:
    ...

def get_client_addr(scope: WWWScope) -> str:
    ...

def get_path_with_query_string(scope: WWWScope) -> str:
    ...

