"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Optional

TRACE_LOG_LEVEL: int
class ColourizedFormatter(logging.Formatter):
    level_name_colors: Any = ...
    use_colors: Any = ...
    def __init__(self, fmt: Optional[str] = ..., datefmt: Optional[str] = ..., style: str = ..., use_colors: Optional[bool] = ...) -> None:
        ...
    
    def color_level_name(self, level_name: str, level_no: int) -> str:
        ...
    
    def should_use_colors(self) -> bool:
        ...
    
    def formatMessage(self, record: logging.LogRecord) -> str:
        ...
    


class DefaultFormatter(ColourizedFormatter):
    def should_use_colors(self) -> bool:
        ...
    


class AccessFormatter(ColourizedFormatter):
    status_code_colours: Any = ...
    def get_status_code(self, status_code: int) -> str:
        ...
    
    def formatMessage(self, record: logging.LogRecord) -> str:
        ...
    


