"""
This type stub file was generated by pyright.
"""

from gunicorn.workers.base import Worker
from typing import Any

class UvicornWorker(Worker):
    CONFIG_KWARGS: Any = ...
    config: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def init_process(self) -> None:
        ...
    
    def init_signals(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    async def callback_notify(self) -> None:
        ...
    


class UvicornH11Worker(UvicornWorker):
    CONFIG_KWARGS: Any = ...


