import collections
from typing import Any

class DictStack(list, collections.abc.Mapping):
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any): ...
    push: Any = ...
    def __contains__(self, other: Any): ...
    def __len__(self): ...
