from distutils.ccompiler import CCompiler
from typing import Any, Optional

PLAT_SPEC_TO_RUNTIME: Any
PLAT_TO_VCVARS: Any

class MSVCCompiler(CCompiler):
    compiler_type: str = ...
    executables: Any = ...
    src_extensions: Any = ...
    res_extension: str = ...
    obj_extension: str = ...
    static_lib_extension: str = ...
    shared_lib_extension: str = ...
    static_lib_format: str = ...
    shared_lib_format: str = ...
    exe_extension: str = ...
    plat_name: Any = ...
    initialized: bool = ...
    def __init__(self, verbose: int = ..., dry_run: int = ..., force: int = ...) -> None: ...
    cc: Any = ...
    linker: Any = ...
    lib: Any = ...
    rc: Any = ...
    mc: Any = ...
    mt: Any = ...
    preprocess_options: Any = ...
    compile_options: Any = ...
    compile_options_debug: Any = ...
    ldflags_exe: Any = ...
    ldflags_exe_debug: Any = ...
    ldflags_shared: Any = ...
    ldflags_shared_debug: Any = ...
    ldflags_static: Any = ...
    ldflags_static_debug: Any = ...
    def initialize(self, plat_name: Optional[Any] = ...) -> None: ...
    def object_filenames(self, source_filenames: Any, strip_dir: int = ..., output_dir: str = ...): ...
    def compile(self, sources: Any, output_dir: Optional[Any] = ..., macros: Optional[Any] = ..., include_dirs: Optional[Any] = ..., debug: int = ..., extra_preargs: Optional[Any] = ..., extra_postargs: Optional[Any] = ..., depends: Optional[Any] = ...): ...
    def create_static_lib(self, objects: Any, output_libname: Any, output_dir: Optional[Any] = ..., debug: int = ..., target_lang: Optional[Any] = ...) -> None: ...
    def link(self, target_desc: Any, objects: Any, output_filename: Any, output_dir: Optional[Any] = ..., libraries: Optional[Any] = ..., library_dirs: Optional[Any] = ..., runtime_library_dirs: Optional[Any] = ..., export_symbols: Optional[Any] = ..., debug: int = ..., extra_preargs: Optional[Any] = ..., extra_postargs: Optional[Any] = ..., build_temp: Optional[Any] = ..., target_lang: Optional[Any] = ...) -> None: ...
    def spawn(self, cmd: Any): ...
    def library_dir_option(self, dir: Any): ...
    def runtime_library_dir_option(self, dir: Any) -> None: ...
    def library_option(self, lib: Any): ...
    def find_library_file(self, dirs: Any, lib: Any, debug: int = ...): ...
