from typing import Any, Optional

def make_tarball(base_name: Any, base_dir: Any, compress: str = ..., verbose: int = ..., dry_run: int = ..., owner: Optional[Any] = ..., group: Optional[Any] = ...): ...
def make_zipfile(base_name: Any, base_dir: Any, verbose: int = ..., dry_run: int = ...): ...

ARCHIVE_FORMATS: Any

def check_archive_formats(formats: Any): ...
def make_archive(base_name: Any, format: Any, root_dir: Optional[Any] = ..., base_dir: Optional[Any] = ..., verbose: int = ..., dry_run: int = ..., owner: Optional[Any] = ..., group: Optional[Any] = ...): ...
