from typing import Any

def mkpath(name: Any, mode: int = ..., verbose: int = ..., dry_run: int = ...): ...
def create_tree(base_dir: Any, files: Any, mode: int = ..., verbose: int = ..., dry_run: int = ...) -> None: ...
def copy_tree(src: Any, dst: Any, preserve_mode: int = ..., preserve_times: int = ..., preserve_symlinks: int = ..., update: int = ..., verbose: int = ..., dry_run: int = ...): ...
def remove_tree(directory: Any, verbose: int = ..., dry_run: int = ...) -> None: ...
def ensure_relative(path: Any): ...
