from distutils.errors import *
from typing import Any, Optional

longopt_pat: str
longopt_re: Any
neg_alias_re: Any
longopt_xlate: Any

class FancyGetopt:
    option_table: Any = ...
    option_index: Any = ...
    alias: Any = ...
    negative_alias: Any = ...
    short_opts: Any = ...
    long_opts: Any = ...
    short2long: Any = ...
    attr_name: Any = ...
    takes_arg: Any = ...
    option_order: Any = ...
    def __init__(self, option_table: Optional[Any] = ...) -> None: ...
    def set_option_table(self, option_table: Any) -> None: ...
    def add_option(self, long_option: Any, short_option: Optional[Any] = ..., help_string: Optional[Any] = ...) -> None: ...
    def has_option(self, long_option: Any): ...
    def get_attr_name(self, long_option: Any): ...
    def set_aliases(self, alias: Any) -> None: ...
    def set_negative_aliases(self, negative_alias: Any) -> None: ...
    def getopt(self, args: Optional[Any] = ..., object: Optional[Any] = ...): ...
    def get_option_order(self): ...
    def generate_help(self, header: Optional[Any] = ...): ...
    def print_help(self, header: Optional[Any] = ..., file: Optional[Any] = ...) -> None: ...

def fancy_getopt(options: Any, negative_opt: Any, object: Any, args: Any): ...

WS_TRANS: Any

def wrap_text(text: Any, width: Any): ...
def translate_longopt(opt: Any): ...

class OptionDummy:
    def __init__(self, options: Any = ...) -> None: ...
