from typing import Any, Optional

def copy_file(src: Any, dst: Any, preserve_mode: int = ..., preserve_times: int = ..., update: int = ..., link: Optional[Any] = ..., verbose: int = ..., dry_run: int = ...): ...
def move_file(src: Any, dst: Any, verbose: int = ..., dry_run: int = ...): ...
def write_file(filename: Any, contents: Any) -> None: ...
