from typing import Any

DEBUG: int
INFO: int
WARN: int
ERROR: int
FATAL: int

class Log:
    threshold: Any = ...
    def __init__(self, threshold: Any = ...) -> None: ...
    def log(self, level: Any, msg: Any, *args: Any) -> None: ...
    def debug(self, msg: Any, *args: Any) -> None: ...
    def info(self, msg: Any, *args: Any) -> None: ...
    def warn(self, msg: Any, *args: Any) -> None: ...
    def error(self, msg: Any, *args: Any) -> None: ...
    def fatal(self, msg: Any, *args: Any) -> None: ...

log: Any
debug: Any
info: Any
warn: Any
error: Any
fatal: Any

def set_threshold(level: Any): ...
def set_verbosity(v: Any) -> None: ...
