from .errors import DistutilsPlatformError as DistutilsPlatformError
from typing import Any, Optional

IS_PYPY: Any
PREFIX: Any
EXEC_PREFIX: Any
BASE_PREFIX: Any
BASE_EXEC_PREFIX: Any
project_base: Any
python_build: Any
build_flags: str

def get_python_version(): ...
def get_python_inc(plat_specific: int = ..., prefix: Optional[Any] = ...): ...
def get_python_lib(plat_specific: int = ..., standard_lib: int = ..., prefix: Optional[Any] = ...): ...
def customize_compiler(compiler: Any) -> None: ...
def get_config_h_filename(): ...
def get_makefile_filename(): ...
def parse_config_h(fp: Any, g: Optional[Any] = ...): ...
def parse_makefile(fn: Any, g: Optional[Any] = ...): ...
def expand_makefile_vars(s: Any, vars: Any): ...
def get_config_vars(*args: Any): ...
def get_config_var(name: Any): ...
