from typing import Any, Optional

def get_host_platform(): ...
def get_platform(): ...

MACOSX_VERSION_VAR: str

def get_macosx_target_ver_from_syscfg(): ...
def get_macosx_target_ver(): ...
def split_version(s: Any): ...
def convert_path(pathname: Any): ...
def change_root(new_root: Any, pathname: Any): ...
def check_environ() -> None: ...
def subst_vars(s: Any, local_vars: Any): ...
def grok_environment_error(exc: Any, prefix: str = ...): ...
def split_quoted(s: Any): ...
def execute(func: Any, args: Any, msg: Optional[Any] = ..., verbose: int = ..., dry_run: int = ...) -> None: ...
def strtobool(val: Any): ...
def byte_compile(py_files: Any, optimize: int = ..., force: int = ..., prefix: Optional[Any] = ..., base_dir: Optional[Any] = ..., verbose: int = ..., dry_run: int = ..., direct: Optional[Any] = ...) -> None: ...
def rfc822_escape(header: Any): ...
