from typing import Any, Optional

def suppress_known_deprecation() -> None: ...

class Version:
    def __init__(self, vstring: Optional[Any] = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...

class StrictVersion(Version):
    version_re: Any = ...
    version: Any = ...
    prerelease: Any = ...
    def parse(self, vstring: Any) -> None: ...

class LooseVersion(Version):
    component_re: Any = ...
    vstring: Any = ...
    version: Any = ...
    def parse(self, vstring: Any) -> None: ...
