import typing as t

SALT_CHARS: str
DEFAULT_PBKDF2_ITERATIONS: int

def pbkdf2_hex(data: t.Union[str, bytes], salt: t.Union[str, bytes], iterations: int=..., keylen: t.Optional[int]=..., hashfunc: t.Optional[t.Union[str, t.Callable]]=...) -> str: ...
def pbkdf2_bin(data: t.Union[str, bytes], salt: t.Union[str, bytes], iterations: int=..., keylen: t.Optional[int]=..., hashfunc: t.Optional[t.Union[str, t.Callable]]=...) -> bytes: ...
def safe_str_cmp(a: str, b: str) -> bool: ...
def gen_salt(length: int) -> str: ...
def generate_password_hash(password: str, method: str=..., salt_length: int=...) -> str: ...
def check_password_hash(pwhash: str, password: str) -> bool: ...
def safe_join(directory: str, *pathnames: str) -> t.Optional[str]: ...
