import typing as t
from typing import Any

class UserAgent:
    platform: t.Optional[str] = ...
    browser: t.Optional[str] = ...
    version: t.Optional[str] = ...
    language: t.Optional[str] = ...
    string: Any = ...
    def __init__(self, string: str) -> None: ...
    def __bool__(self) -> bool: ...
    def to_header(self) -> str: ...
