from ... import util as util
from .kinterbasdb import FBDialect_kinterbasdb as FBDialect_kinterbasdb
from typing import Any

class FBDialect_fdb(FBDialect_kinterbasdb):
    supports_statement_cache: bool = ...
    def __init__(self, enable_rowcount: bool = ..., retaining: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def dbapi(cls): ...
    def create_connect_args(self, url: Any): ...
dialect = FBDialect_fdb
