"""
This type stub file was generated by pyright.
"""

from typing import Any

def create_engine(url: Any, **kwargs: Any):
    ...

def engine_from_config(configuration: Any, prefix: str = ..., **kwargs: Any):
    ...

