"""
This type stub file was generated by pyright.
"""

from . import base as base
from typing import Any

class MockConnection(base.Connectable):
    def __init__(self, dialect: Any, execute: Any) -> None:
        ...
    
    engine: Any = ...
    dialect: Any = ...
    name: Any = ...
    def schema_for_object(self, obj: Any):
        ...
    
    def connect(self, **kwargs: Any):
        ...
    
    def execution_options(self, **kw: Any):
        ...
    
    def compiler(self, statement: Any, parameters: Any, **kwargs: Any):
        ...
    
    def create(self, entity: Any, **kwargs: Any) -> None:
        ...
    
    def drop(self, entity: Any, **kwargs: Any) -> None:
        ...
    
    def execute(self, object_: Any, *multiparams: Any, **params: Any) -> None:
        ...
    


def create_mock_engine(url: Any, executor: Any, **kw: Any):
    ...

