"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class URL:
    def __new__(self, *arg: Any, **kw: Any):
        ...
    
    @classmethod
    def create(cls, drivername: Any, username: Optional[Any] = ..., password: Optional[Any] = ..., host: Optional[Any] = ..., port: Optional[Any] = ..., database: Optional[Any] = ..., query: Any = ...):
        ...
    
    def set(self, drivername: Optional[Any] = ..., username: Optional[Any] = ..., password: Optional[Any] = ..., host: Optional[Any] = ..., port: Optional[Any] = ..., database: Optional[Any] = ..., query: Optional[Any] = ...):
        ...
    
    def update_query_string(self, query_string: Any, append: bool = ...):
        ...
    
    def update_query_pairs(self, key_value_pairs: Any, append: bool = ...):
        ...
    
    def update_query_dict(self, query_parameters: Any, append: bool = ...):
        ...
    
    def difference_update_query(self, names: Any):
        ...
    
    def normalized_query(self):
        ...
    
    def __to_string__(self, hide_password: bool = ...):
        ...
    
    def render_as_string(self, hide_password: bool = ...):
        ...
    
    def __hash__(self) -> Any:
        ...
    
    def __eq__(self, other: Any) -> Any:
        ...
    
    def __ne__(self, other: Any) -> Any:
        ...
    
    def get_backend_name(self):
        ...
    
    def get_driver_name(self):
        ...
    
    def get_dialect(self):
        ...
    
    def translate_connect_args(self, names: Optional[Any] = ..., **kw: Any):
        ...
    


def make_url(name_or_url: Any):
    ...

