"""
This type stub file was generated by pyright.
"""

from typing import Any

def connection_memoize(key: Any):
    ...

class TransactionalContext:
    def __enter__(self):
        ...
    
    def __exit__(self, type_: Any, value: Any, traceback: Any) -> None:
        ...
    


