from distutils.errors import DistutilsError
from typing import Any, Optional

class UnrecognizedFormat(DistutilsError): ...

def default_filter(src: Any, dst: Any): ...
def unpack_archive(filename: Any, extract_dir: Any, progress_filter: Any = ..., drivers: Optional[Any] = ...) -> None: ...
def unpack_directory(filename: Any, extract_dir: Any, progress_filter: Any = ...) -> None: ...
def unpack_zipfile(filename: Any, extract_dir: Any, progress_filter: Any = ...) -> None: ...
def unpack_tarfile(filename: Any, extract_dir: Any, progress_filter: Any = ...): ...

extraction_drivers: Any
