import setuptools
from typing import Any, Optional

class SetupRequirementsError(BaseException):
    specifiers: Any = ...
    def __init__(self, specifiers: Any) -> None: ...

class Distribution(setuptools.dist.Distribution):
    def fetch_build_eggs(self, specifiers: Any) -> None: ...
    @classmethod
    def patch(cls) -> None: ...

class _BuildMetaBackend:
    def run_setup(self, setup_script: str = ...) -> None: ...
    def get_requires_for_build_wheel(self, config_settings: Optional[Any] = ...): ...
    def get_requires_for_build_sdist(self, config_settings: Optional[Any] = ...): ...
    def prepare_metadata_for_build_wheel(self, metadata_directory: Any, config_settings: Optional[Any] = ...): ...
    def build_wheel(self, wheel_directory: Any, config_settings: Optional[Any] = ..., metadata_directory: Optional[Any] = ...): ...
    def build_sdist(self, sdist_directory: Any, config_settings: Optional[Any] = ...): ...

class _BuildMetaLegacyBackend(_BuildMetaBackend):
    def run_setup(self, setup_script: str = ...) -> None: ...

get_requires_for_build_wheel: Any
get_requires_for_build_sdist: Any
prepare_metadata_for_build_wheel: Any
build_wheel: Any
build_sdist: Any
__legacy__: Any
