from ._imp import find_module as find_module
from typing import Any, Optional

class Require:
    def __init__(self, name: Any, requested_version: Any, module: Any, homepage: str = ..., attribute: Optional[Any] = ..., format: Optional[Any] = ...) -> None: ...
    def full_name(self): ...
    def version_ok(self, version: Any): ...
    def get_version(self, paths: Optional[Any] = ..., default: str = ...): ...
    def is_present(self, paths: Optional[Any] = ...): ...
    def is_current(self, paths: Optional[Any] = ...): ...

def get_module_constant(module: Any, symbol: Any, default: int = ..., paths: Optional[Any] = ...): ...
def extract_constant(code: Any, symbol: Any, default: int = ...): ...
