from typing import Any

def get_unpatched(item: Any): ...
def get_unpatched_class(cls): ...
def patch_all() -> None: ...
def patch_func(replacement: Any, target_mod: Any, func_name: Any) -> None: ...
def get_unpatched_function(candidate: Any): ...
def patch_for_msvc_specialized_compiler(): ...
