"""
This type stub file was generated by pyright.
"""

from typing import Any

class _AsyncGeneratorContextManager:
    gen: Any = ...
    __doc__: Any = ...
    def __init__(self, func: Any, args: Any, kwds: Any) -> None:
        ...
    
    async def __aenter__(self):
        ...
    
    async def __aexit__(self, typ: Any, value: Any, traceback: Any):
        ...
    


def asynccontextmanager(func: Any):
    ...

