"""
This type stub file was generated by pyright.
"""

from typing import Any

class _ModuleRegistry:
    module_registry: Any = ...
    prefix: Any = ...
    def __init__(self, prefix: str = ...) -> None:
        ...
    
    def preload_module(self, *deps: Any):
        ...
    
    def import_prefix(self, path: Any) -> None:
        ...
    


preloaded: Any
preload_module: Any
