"""
This type stub file was generated by pyright.
"""

from asgiref.typing import ASGI2Application as ASGI2Application, ASGIReceiveCallable as ASGIReceiveCallable, ASGISendCallable as ASGISendCallable, Scope as Scope
from typing import Any

class ASGI2Middleware:
    app: Any = ...
    def __init__(self, app: ASGI2Application) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


