"""
This type stub file was generated by pyright.
"""

from asgiref.typing import ASGI3Application as ASGI3Application, ASGIReceiveCallable as ASGIReceiveCallable, ASGISendCallable as ASGISendCallable, WWWScope as WWWScope
from typing import Any

PLACEHOLDER_FORMAT: Any
def message_with_placeholders(message: Any) -> Any:
    ...

class MessageLoggerMiddleware:
    task_counter: int = ...
    app: Any = ...
    logger: Any = ...
    def __init__(self, app: ASGI3Application) -> None:
        ...
    
    async def __call__(self, scope: WWWScope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


