"""
This type stub file was generated by pyright.
"""

from asgiref.typing import ASGI3Application as ASGI3Application, ASGIReceiveCallable as ASGIReceiveCallable, ASGISendCallable as ASGISendCallable, Scope as Scope
from typing import Any, List, Optional, Union

class ProxyHeadersMiddleware:
    app: Any = ...
    trusted_hosts: Any = ...
    always_trust: Any = ...
    def __init__(self, app: ASGI3Application, trusted_hosts: Union[List[str], str] = ...) -> None:
        ...
    
    def get_trusted_client_host(self, x_forwarded_for_hosts: List[str]) -> Optional[str]:
        ...
    
    async def __call__(self, scope: Scope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


