from distutils.core import Command
from msilib import Dialog
from typing import Any

class PyDialog(Dialog):
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def title(self, title: Any) -> None: ...
    def back(self, title: Any, next: Any, name: str = ..., active: int = ...): ...
    def cancel(self, title: Any, next: Any, name: str = ..., active: int = ...): ...
    def next(self, title: Any, next: Any, name: str = ..., active: int = ...): ...
    def xbutton(self, name: Any, title: Any, next: Any, xpos: Any): ...

class bdist_msi(Command):
    description: str = ...
    user_options: Any = ...
    boolean_options: Any = ...
    all_versions: Any = ...
    other_version: str = ...
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    bdist_dir: Any = ...
    plat_name: Any = ...
    keep_temp: int = ...
    no_target_compile: int = ...
    no_target_optimize: int = ...
    target_version: Any = ...
    dist_dir: Any = ...
    skip_build: Any = ...
    install_script: Any = ...
    pre_install_script: Any = ...
    versions: Any = ...
    def initialize_options(self) -> None: ...
    install_script_key: Any = ...
    def finalize_options(self) -> None: ...
    db: Any = ...
    def run(self) -> None: ...
    def add_files(self) -> None: ...
    def add_find_python(self) -> None: ...
    def add_scripts(self) -> None: ...
    def add_ui(self) -> None: ...
    def get_installer_filename(self, fullname: Any): ...
