from distutils.errors import *
from . import py37compat as py37compat
from distutils.core import Command
from typing import Any

extension_name_re: Any

def show_compilers() -> None: ...

class build_ext(Command):
    description: str = ...
    sep_by: Any = ...
    user_options: Any = ...
    boolean_options: Any = ...
    help_options: Any = ...
    extensions: Any = ...
    build_lib: Any = ...
    plat_name: Any = ...
    build_temp: Any = ...
    inplace: int = ...
    package: Any = ...
    include_dirs: Any = ...
    define: Any = ...
    undef: Any = ...
    libraries: Any = ...
    library_dirs: Any = ...
    rpath: Any = ...
    link_objects: Any = ...
    debug: Any = ...
    force: Any = ...
    compiler: Any = ...
    swig: Any = ...
    swig_cpp: Any = ...
    swig_opts: Any = ...
    user: Any = ...
    parallel: Any = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def check_extensions_list(self, extensions: Any) -> None: ...
    def get_source_files(self): ...
    def get_outputs(self): ...
    def build_extensions(self) -> None: ...
    def build_extension(self, ext: Any) -> None: ...
    def swig_sources(self, sources: Any, extension: Any): ...
    def find_swig(self): ...
    def get_ext_fullpath(self, ext_name: Any): ...
    def get_ext_fullname(self, ext_name: Any): ...
    def get_ext_filename(self, ext_name: Any): ...
    def get_export_symbols(self, ext: Any): ...
    def get_libraries(self, ext: Any): ...
