from distutils.errors import *
from distutils.core import Command
from typing import Any

class build_py(Command):
    description: str = ...
    user_options: Any = ...
    boolean_options: Any = ...
    negative_opt: Any = ...
    build_lib: Any = ...
    py_modules: Any = ...
    package: Any = ...
    package_data: Any = ...
    package_dir: Any = ...
    compile: int = ...
    optimize: int = ...
    force: Any = ...
    def initialize_options(self) -> None: ...
    packages: Any = ...
    data_files: Any = ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def get_data_files(self): ...
    def find_data_files(self, package: Any, src_dir: Any): ...
    def build_package_data(self) -> None: ...
    def get_package_dir(self, package: Any): ...
    def check_package(self, package: Any, package_dir: Any): ...
    def check_module(self, module: Any, module_file: Any): ...
    def find_package_modules(self, package: Any, package_dir: Any): ...
    def find_modules(self): ...
    def find_all_modules(self): ...
    def get_source_files(self): ...
    def get_module_outfile(self, build_dir: Any, package: Any, module: Any): ...
    def get_outputs(self, include_bytecode: int = ...): ...
    def build_module(self, module: Any, module_file: Any, package: Any): ...
    def build_modules(self) -> None: ...
    def build_packages(self) -> None: ...
    def byte_compile(self, files: Any) -> None: ...
