from distutils.core import Command
from docutils.utils import Reporter
from typing import Any, Optional

class SilentReporter(Reporter):
    messages: Any = ...
    def __init__(self, source: Any, report_level: Any, halt_level: Any, stream: Optional[Any] = ..., debug: int = ..., encoding: str = ..., error_handler: str = ...) -> None: ...
    def system_message(self, level: Any, message: Any, *children: Any, **kwargs: Any): ...

HAS_DOCUTILS: bool

class check(Command):
    description: str = ...
    user_options: Any = ...
    boolean_options: Any = ...
    restructuredtext: int = ...
    metadata: int = ...
    strict: int = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def warn(self, msg: Any): ...
    def run(self) -> None: ...
    def check_metadata(self) -> None: ...
    def check_restructuredtext(self) -> None: ...
