import distutils.command.build_py as orig
from setuptools.extern.more_itertools import unique_everseen as unique_everseen
from typing import Any

def make_writable(target: Any) -> None: ...

class build_py(orig.build_py):
    package_data: Any = ...
    exclude_package_data: Any = ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    data_files: Any = ...
    def __getattr__(self, attr: Any): ...
    def build_module(self, module: Any, module_file: Any, package: Any): ...
    def get_data_files_without_manifest(self): ...
    def find_data_files(self, package: Any, src_dir: Any): ...
    def build_package_data(self) -> None: ...
    manifest_files: Any = ...
    def analyze_manifest(self) -> None: ...
    def get_data_files(self) -> None: ...
    def check_package(self, package: Any, package_dir: Any): ...
    packages_checked: Any = ...
    def initialize_options(self) -> None: ...
    def get_package_dir(self, package: Any): ...
    def exclude_data_files(self, package: Any, src_dir: Any, files: Any): ...

def assert_relative(path: Any): ...
