import distutils.command.install_scripts as orig
from typing import Any

class install_scripts(orig.install_scripts):
    no_ep: bool = ...
    def initialize_options(self) -> None: ...
    outfiles: Any = ...
    def run(self) -> None: ...
    def write_script(self, script_name: Any, contents: Any, mode: str = ..., *ignored: Any) -> None: ...
