from setuptools import Command
from typing import Any

def config_file(kind: str = ...): ...
def edit_config(filename: Any, settings: Any, dry_run: bool = ...): ...

class option_base(Command):
    user_options: Any = ...
    boolean_options: Any = ...
    global_config: Any = ...
    user_config: Any = ...
    filename: Any = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...

class setopt(option_base):
    description: str = ...
    user_options: Any = ...
    boolean_options: Any = ...
    command: Any = ...
    option: Any = ...
    set_value: Any = ...
    remove: Any = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
