from ... import pool as pool, util as util
from .pysqlite import SQLiteDialect_pysqlite as SQLiteDialect_pysqlite
from typing import Any

class SQLiteDialect_pysqlcipher(SQLiteDialect_pysqlite):
    driver: str = ...
    supports_statement_cache: bool = ...
    pragmas: Any = ...
    @classmethod
    def dbapi(cls): ...
    @classmethod
    def get_pool_class(cls, url: Any): ...
    def on_connect_url(self, url: Any): ...
    def create_connect_args(self, url: Any): ...
dialect = SQLiteDialect_pysqlcipher
