from ...util import langhelpers as langhelpers, py3k as py3k
from .mysqldb import MySQLDialect_mysqldb as MySQLDialect_mysqldb
from typing import Any, Optional

class MySQLDialect_pymysql(MySQLDialect_mysqldb):
    driver: str = ...
    supports_statement_cache: bool = ...
    description_encoding: Any = ...
    supports_unicode_statements: bool = ...
    supports_unicode_binds: bool = ...
    def supports_server_side_cursors(self): ...
    @classmethod
    def dbapi(cls): ...
    def create_connect_args(self, url: Any, _translate_args: Optional[Any] = ...): ...
    def is_disconnect(self, e: Any, connection: Any, cursor: Any): ...
dialect = MySQLDialect_pymysql
