"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class ScopedSessionMixin:
    def __call__(self, **kw: Any):
        ...
    
    def configure(self, **kwargs: Any) -> None:
        ...
    


class scoped_session(ScopedSessionMixin):
    session_factory: Any = ...
    registry: Any = ...
    def __init__(self, session_factory: Any, scopefunc: Optional[Any] = ...) -> None:
        ...
    
    def remove(self) -> None:
        ...
    
    def query_property(self, query_cls: Optional[Any] = ...):
        ...
    


ScopedSession = scoped_session
