"""
This type stub file was generated by pyright.
"""

from typing import Any, ClassVar

class immutabledict:
    __hash__: ClassVar[None] = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get(self, *args, **kwargs) -> Any:
        ...
    
    def items(self, *args, **kwargs) -> Any:
        ...
    
    def keys(self, *args, **kwargs) -> Any:
        ...
    
    def merge_with(self, *args, **kwargs) -> Any:
        ...
    
    def union(self, *args, **kwargs) -> Any:
        ...
    
    def values(self, *args, **kwargs) -> Any:
        ...
    
    def __contains__(self, other) -> Any:
        ...
    
    def __eq__(self, other) -> Any:
        ...
    
    def __ge__(self, other) -> Any:
        ...
    
    def __getitem__(self, index) -> Any:
        ...
    
    def __gt__(self, other) -> Any:
        ...
    
    def __iter__(self) -> Any:
        ...
    
    def __le__(self, other) -> Any:
        ...
    
    def __len__(self) -> Any:
        ...
    
    def __lt__(self, other) -> Any:
        ...
    
    def __ne__(self, other) -> Any:
        ...
    
    def __reduce__(self) -> Any:
        ...
    


