from typing import Any, ClassVar

class BaseRow:
    _data: ClassVar[getset_descriptor] = ...
    _key_style: ClassVar[getset_descriptor] = ...
    _keymap: ClassVar[getset_descriptor] = ...
    _parent: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def _filter_on_values(self, *args, **kwargs) -> Any: ...
    def _get_by_key_impl(self, *args, **kwargs) -> Any: ...
    def _get_by_key_impl_mapping(self, *args, **kwargs) -> Any: ...
    def _values_impl(self, *args, **kwargs) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __hash__(self) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> Any: ...
    def __reduce__(self) -> Any: ...

class tuplegetter:
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...

def safe_rowproxy_reconstructor(*args, **kwargs) -> Any: ...
