"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def str_to_datetime_processor_factory(regexp: Any, type_: Any):
    ...

def py_fallback():
    ...

def to_unicode_processor_factory(encoding: Any, errors: Optional[Any] = ...):
    ...

def to_conditional_unicode_processor_factory(encoding: Any, errors: Optional[Any] = ...):
    ...

def to_decimal_processor_factory(target_class: Any, scale: Any):
    ...

