from . import util as util
from sqlalchemy.cprocessors import DecimalResultProcessor as DecimalResultProcessor, UnicodeResultProcessor as UnicodeResultProcessor, int_to_boolean as int_to_boolean, str_to_date as str_to_date, str_to_datetime as str_to_datetime, str_to_time as str_to_time, to_float as to_float, to_str as to_str
from typing import Any, Optional

def str_to_datetime_processor_factory(regexp: Any, type_: Any): ...
def py_fallback(): ...
def to_unicode_processor_factory(encoding: Any, errors: Optional[Any] = ...): ...
def to_conditional_unicode_processor_factory(encoding: Any, errors: Optional[Any] = ...): ...
def to_decimal_processor_factory(target_class: Any, scale: Any): ...
