"""
This type stub file was generated by pyright.
"""

import textwrap
import typing as t
from contextlib import contextmanager

class TextWrapper(textwrap.TextWrapper):
    @contextmanager
    def extra_indent(self, indent: str) -> t.Iterator[None]:
        ...
    
    def indent_only(self, text: str) -> str:
        ...
    


